//#pragma config(Motor,  port1,           m1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           m2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           m3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           m4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           m5,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           m6,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           m7,            tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port8,           m8,            tmotorVex393_MC29, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task autonomous()
{
		motor[port2] = 127;
		motor[port4]= 127;
		motor[port3] = 127;
		motor[port5]= 127;
		wait1Msec(1000); //run at full speed for 1 second

		motor[port2] = 120;
		motor[port3]= 120;
		motor[port4] = -60;
		motor[port5] = -60;
		wait1Msec(1000); //turn robot to the right facing first big thing

		motor[port2] = 127;
		motor[port4]= 127;
		motor[port3] = 127;
		motor[port5]= 127;
		wait1Msec(1000); //run at full speed for 1 second
}

task userControl()
{
	while(true) {
		//JOYSTICK/BASE WHEELS
		motor[port2] = -vexRT[Ch2]; //Full power is 127; 2nd joystick y axis (up and down)
		motor[port3] = -vexRT[Ch2]; //for some reason motors 2 and 3 were going the opposite direction so I just reversed them
		motor[port4] = vexRT[Ch3];
		motor[port5] = vexRT[Ch3];

		//RIGHT TRIGGER/ARM
	  if(vexRT[Btn6U] == 1)//when the up trigger is pressed
	  {
	  motor[port6] = -127;
	  motor[port7] = 127;
	  }
	  else if(vexRT[Btn6D] == 1)//when the down trigger is pressed
	  {
	  motor[port6] = 127;
	  motor[port7] = -127;
	  }
	  else
	  {
	  motor[port6] = 0;
	  motor[port7] = 0;
	  }

	  //LEFT TRIGGER/CLAW

	  if(vexRT[Btn5U] == 1)//when the up trigger is pressed
	  {
	  motor[port8] = 127;
	  }
	  else if(vexRT[Btn5D] == 1)//when the down trigger is pressed
	  {
	  motor[port8] = -127;
	  }
	  else
	  {
	  motor[port8] = 0;
	  }


		wait1Msec(50);
	}
}

task main() {
	startTask(autonomous);
	startTask(userControl);
}
