//#pragma config(Motor,  port1,           m1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           m2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           m3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           m4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           m5,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           m6,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           m7,            tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port8,           m8,            tmotorVex393_MC29, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task autonomous()
{
		motor[port2] = 127;
		motor[port4]= 127;
		motor[port3] = 127;
		motor[port5]= 127;
		wait1Msec(4000); //run at full speed for 6 second (6 feet)

		motor[port2] = 120;
		motor[port3]= 120;
		motor[port4] = -60;
		motor[port5] = -60;
		wait1Msec(2000); //turn robot to the right (about 135 degrees) facing first big thing

		motor[port2] = 127;
		motor[port4]= 127;
		motor[port3] = 127;
		motor[port5]= 127;
		wait1Msec(2000); //run at full speed for 2 second

		motor[port2] = 120;
		motor[port3]= 120;
		motor[port4] = -60;
		motor[port5] = -60;
		wait1Msec(2000); //turn robot to the right (about 90 degrees) facing first big thing towards base

		motor[port2] = 127;
		motor[port4]= 127;
		motor[port3] = 127;
		motor[port5]= 127;

		wait1Msec(4000); //run at full speed for 4 second (9 feet)ramming the cone into the home base

		motor[port2] = 120;
		motor[port3]= 120;
		motor[port4] = -60;
		motor[port5] = -60;
		wait1Msec(2000); //turn robot to the right (about 180 degrees) facing back out towards open area

}

task main()
{
	while(true) {
		//JOYSTICK/BASE WHEELS
		motor[port2] = -vexRT[Ch2]; //Full power is 127; 2nd joystick y axis (up and down)
		motor[port3] = -vexRT[Ch2]; //for some reason motors 2 and 3 were going the opposite direction so I just reversed them
		motor[port4] = vexRT[Ch3];
		motor[port5] = vexRT[Ch3];

		//LEFT TRIGGER/CLAW

	  if(vexRT[Btn5U] == 1)//when the up trigger is pressed
	  {
	  motor[port8] = -127;
	  }
	  else
	  {
	  motor[port8] = 0;
	  }

		//RIGHT TRIGGER/ARM
	  if(vexRT[Btn6U] == 1)//when the up trigger is pressed
	  {
	  motor[port6] = 127;
	  motor[port7] = -127;
	  }
	  else if(vexRT[Btn6D] == 1)//when the down trigger is pressed
	  {
	  motor[port6] = -127;
	  motor[port7] = 127;
	  }
	  else
	  {
	  motor[port6] = 0;
	  motor[port7] = 0;
	  }




		wait1Msec(50);
	}
}
/*
task main() {
	startTask(autonomous);
	startTask(userControl);
}
*/
